name: my_gps_app
description: "K-Path GPS Tracking Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.1
  latlong2: ^0.9.1
  flutter_map: ^6.2.1
  flutter_tts: ^3.8.5
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  path_provider: ^2.1.3
  share_plus: ^7.2.1
  app_settings: ^5.1.1
  geocoding: ^3.0.0 # 🛠️ [★해결 핵심] 주소지 명칭 변환용 엔진 라이브러리 정식 등록 완료!
  url_launcher: ^6.3.0 # 하단 날씨 및 두루누비 브라우저 딥링크용 도구

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png