allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

// 에러 원인이었던 tasks.register 부분을 아래처럼 단순하게 바꿨습니다.
tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
